import { type ContentSource } from "@/lib/content/sources";

export type DemoArchiveItem = {
  id: string;
  title: string;
  short_summary: string;
  long_summary?: string;
  action_line: string;
  source_name: string;
  source_url: string;
  sources: ContentSource[];
  slug: string;
  published_at: string;
  share_count?: number;
  summary_type: "MUST" | "USEFUL" | "ACTION";
  main_interest: string;
  sub_interest: string;
  thumbnail_url: string | null;
  thumbnail_alt: string | null;
  thumbnail_page_url: string | null;
  thumbnail_license: string | null;
};

const now = new Date().toISOString();

export const DEMO_ARCHIVE_ITEMS: DemoArchiveItem[] = [
  {
    id: "demo-health-1",
    title: "걷기와 하루 리듬",
    short_summary: "짧은 산책은 몸을 무리시키지 않으면서도 하루의 흐름을 정리하는 데 도움을 줄 수 있습니다.",
    long_summary: "많은 연구에서 하루 10~15분의 가벼운 걷기만으로도 혈당 조절과 심폐 기능 유지에 긍정적인 영향을 준다는 결과가 반복적으로 나오고 있습니다. 특히 식후 10분 걷기는 혈당이 급격히 올라가는 것을 막아주는 효과가 있어 당뇨나 혈압을 관리하는 분들에게 권장됩니다. 걷는 시간이 오전이라면 햇빛을 받아 세로토닌 분비를 높이는 부가 효과도 기대할 수 있습니다. 세로토닌은 기분을 안정시키고 낮 동안 집중력을 유지하는 데 도움을 주는 호르몬입니다. 운동화를 따로 갖춰 신지 않아도 편한 신발에 15분 정도 동네 한 바퀴를 돌아오는 것만으로 충분합니다. 무릎이나 관절이 걱정된다면 평지에서 천천히 걷되, 보폭을 너무 크게 벌리지 않는 것이 좋습니다. 중요한 것은 매일 습관처럼 이어가는 리듬이며, 완벽한 운동보다 꾸준한 산책이 장기적으로 더 큰 변화를 만들어 냅니다. 걷기는 도구도, 비용도, 특별한 장소도 필요 없는 가장 접근하기 쉬운 건강 습관입니다.",
    action_line: "오전이나 점심 전후에 10분만 가볍게 걸어보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-health-1",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-health-1", type: "blog" }],
    slug: "sample-health-walking",
    published_at: now,
    share_count: 9,
    summary_type: "USEFUL",
    main_interest: "건강",
    sub_interest: "걷기",
    thumbnail_url: "https://picsum.photos/seed/walking/400/300",
    thumbnail_alt: "공원을 걷는 모습",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-health-2",
    title: "잠들기 전 화면과 수면",
    short_summary: "잠자기 직전 자극을 줄이면 아침에 덜 피곤하게 시작하는 데 도움이 될 수 있습니다.",
    long_summary: "스마트폰이나 TV 화면에서 나오는 청색광은 뇌가 아직 낮이라고 인식하게 만들어 수면 호르몬인 멜라토닌 분비를 늦춥니다. 멜라토닌이 충분히 분비되지 않으면 잠이 드는 데 시간이 오래 걸리고, 수면의 질도 낮아져 다음 날 아침에 피로감이 더 진하게 남습니다. 특히 뉴스나 자극적인 콘텐츠는 뇌를 각성 상태로 유지시키기 때문에 잠자리에 들기 전 20~30분은 화면 없이 보내는 것이 권장됩니다. 대신 책을 읽거나, 따뜻한 물로 족욕을 하거나, 조용한 음악을 틀어두는 방식으로 몸이 수면 모드로 전환되도록 도와줄 수 있습니다. 수면 시간 자체보다 취침과 기상 시간을 일정하게 유지하는 것이 생체 리듬 안정에 더 효과적이라는 연구 결과도 있습니다. 나이가 들수록 깊은 수면 단계가 줄어들기 때문에 잠자리 환경을 조용하고 서늘하게 유지하는 것도 중요합니다. 오늘 하루 화면을 20분만 일찍 끄는 것에서 시작해보세요. 작은 변화지만 며칠 이어지면 아침의 개운함이 달라지는 것을 느낄 수 있습니다.",
    action_line: "오늘은 잠들기 20분 전부터 화면을 멀리해보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-health-2",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-health-2", type: "blog" }],
    slug: "sample-health-sleep",
    published_at: now,
    share_count: 4,
    summary_type: "ACTION",
    main_interest: "건강",
    sub_interest: "수면",
    thumbnail_url: "https://picsum.photos/seed/sleep/400/300",
    thumbnail_alt: "편안한 수면",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-health-3",
    title: "식단 기록과 생활 패턴",
    short_summary: "모든 식사를 자세히 적지 않아도 자주 먹는 시간과 양만 적어두면 생활 패턴을 읽기 쉬워집니다.",
    long_summary: "식단 관리를 처음 시작할 때 많은 분들이 칼로리나 영양소를 꼼꼼하게 기록하려다 금방 포기하는 경우가 많습니다. 전문가들은 오히려 완벽한 기록보다 단순한 패턴 파악이 더 오래 지속 가능하다고 조언합니다. 하루 세 끼 중 어느 끼니를 거르는지, 오후 늦게 간식을 많이 먹는 시간대가 있는지 같은 큰 흐름을 파악하는 것만으로도 개선 방향이 보입니다. 특히 야식 시간이나 폭식이 반복되는 상황을 인식하는 것이 습관 교정의 첫 단계입니다. 식단 앱을 사용하지 않아도 메모장에 시간과 음식 이름만 적는 방식으로도 충분한 데이터가 쌓입니다. 일주일치 기록을 한눈에 보면 나도 몰랐던 식습관의 패턴이 드러나는 경우가 많습니다. 혈당이나 혈압 관리가 필요한 분이라면 의사나 영양사와 이 기록을 공유하면 더 구체적인 조언을 받을 수 있습니다. 오늘은 부담 없이 점심 한 끼의 시간과 메뉴만 적어보는 것에서 시작해보세요.",
    action_line: "오늘은 한 끼만 시간과 양을 간단히 적어보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-health-3",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-health-3", type: "blog" }],
    slug: "sample-health-diet",
    published_at: now,
    share_count: 5,
    summary_type: "USEFUL",
    main_interest: "건강",
    sub_interest: "식단",
    thumbnail_url: "https://picsum.photos/seed/diet/400/300",
    thumbnail_alt: "건강한 식사",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-money-1",
    title: "이번 주 생활 물가",
    short_summary: "이번 주 주요 생활 물가 흐름이 정리되면서 장보기와 외식 계획을 세우기 더 쉬워졌습니다.",
    action_line: "오늘 장보기 전에 자주 사는 품목 가격을 한 번 비교해보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-money-1",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-money-1", type: "news" }],
    slug: "sample-money-living-cost",
    published_at: now,
    share_count: 15,
    summary_type: "MUST",
    main_interest: "돈",
    sub_interest: "생활비",
    thumbnail_url: "https://picsum.photos/seed/market/400/300",
    thumbnail_alt: "마트 장보기",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-money-2",
    title: "연금 확인서 다시 보기",
    short_summary: "정기적으로 보는 항목도 다시 보면 수령 시기나 준비 서류를 더 분명히 정리할 수 있습니다.",
    action_line: "오늘은 연금 관련 알림이나 안내문을 한 번만 확인해보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-money-2",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-money-2", type: "public" }],
    slug: "sample-money-pension",
    published_at: now,
    share_count: 8,
    summary_type: "USEFUL",
    main_interest: "돈",
    sub_interest: "연금",
    thumbnail_url: "https://picsum.photos/seed/pension/400/300",
    thumbnail_alt: "연금 서류",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-money-3",
    title: "절세 서류 한곳에 모으기",
    short_summary: "서류를 찾는 시간이 줄면 신고 시기마다 같은 내용을 다시 확인하는 수고를 덜 수 있습니다.",
    action_line: "오늘은 세금 관련 문서를 한 폴더에만 모아보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-money-3",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-money-3", type: "public" }],
    slug: "sample-money-tax",
    published_at: now,
    share_count: 11,
    summary_type: "ACTION",
    main_interest: "돈",
    sub_interest: "절세",
    thumbnail_url: "https://picsum.photos/seed/tax/400/300",
    thumbnail_alt: "서류 정리",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-news-1",
    title: "오늘의 정책 변화",
    short_summary: "생활과 가까운 제도 변화는 신청 기한이나 혜택 범위를 미리 알아두는 것이 중요합니다.",
    action_line: "오늘은 공공기관 공지 한 건만 가볍게 살펴보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-news-1",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-news-1", type: "public" }],
    slug: "sample-news-policy",
    published_at: now,
    share_count: 12,
    summary_type: "MUST",
    main_interest: "뉴스",
    sub_interest: "정책 변화",
    thumbnail_url: "https://picsum.photos/seed/policy/400/300",
    thumbnail_alt: "정책 뉴스",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-news-2",
    title: "생활과 바로 닿는 지역 소식",
    short_summary: "교통, 행사, 생활 민원 안내 같은 지역 소식은 하루 계획에 직접 도움이 됩니다.",
    action_line: "오늘은 사는 지역 소식 한 건만 확인해보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-news-2",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-news-2", type: "news" }],
    slug: "sample-news-local",
    published_at: now,
    share_count: 7,
    summary_type: "ACTION",
    main_interest: "뉴스",
    sub_interest: "지역 소식",
    thumbnail_url: "https://picsum.photos/seed/local/400/300",
    thumbnail_alt: "지역 소식",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-news-3",
    title: "국제 이슈는 환율과 기름값부터 보세요",
    short_summary: "먼 나라 뉴스라도 생활비와 직접 닿는 값부터 보면 오늘 필요한 판단에 더 도움이 됩니다.",
    action_line: "오늘은 국제 뉴스보다 환율이나 유가 한 줄만 확인해보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-news-3",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-news-3", type: "news" }],
    slug: "sample-news-global",
    published_at: now,
    share_count: 13,
    summary_type: "MUST",
    main_interest: "뉴스",
    sub_interest: "국제이슈",
    thumbnail_url: "https://picsum.photos/seed/global/400/300",
    thumbnail_alt: "국제 뉴스",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-hobby-1",
    title: "책 읽는 시간과 하루의 차분함",
    short_summary: "짧게라도 읽는 시간을 정해두면 바쁜 날에도 마음을 가라앉히는 데 도움이 됩니다.",
    action_line: "오늘은 잠들기 전에 책 5쪽만 읽어보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-hobby-1",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-hobby-1", type: "blog" }],
    slug: "sample-hobby-book",
    published_at: now,
    share_count: 3,
    summary_type: "USEFUL",
    main_interest: "취미",
    sub_interest: "책",
    thumbnail_url: "https://picsum.photos/seed/book/400/300",
    thumbnail_alt: "책 읽기",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-hobby-2",
    title: "여행 준비는 사진 정리부터",
    short_summary: "큰 준비가 아니어도, 가고 싶은 장소를 천천히 모아두는 것만으로도 다음 일정이 선명해집니다.",
    action_line: "오늘은 가보고 싶은 곳 사진 한 장만 저장해보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-hobby-2",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-hobby-2", type: "blog" }],
    slug: "sample-hobby-travel",
    published_at: now,
    share_count: 6,
    summary_type: "ACTION",
    main_interest: "취미",
    sub_interest: "여행",
    thumbnail_url: "https://picsum.photos/seed/travel/400/300",
    thumbnail_alt: "여행 풍경",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-hobby-3",
    title: "사진 한 장 남기면 하루가 또렷해집니다",
    short_summary: "거창한 기록이 아니어도 한 장의 사진은 오늘 기억을 정리하는 데 충분할 수 있습니다.",
    action_line: "오늘 마음에 든 장면을 한 장만 찍어두세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-hobby-3",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-hobby-3", type: "blog" }],
    slug: "sample-hobby-photo",
    published_at: now,
    share_count: 4,
    summary_type: "ACTION",
    main_interest: "취미",
    sub_interest: "사진",
    thumbnail_url: "https://picsum.photos/seed/photo/400/300",
    thumbnail_alt: "사진 촬영",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-family-1",
    title: "가족 일정 맞추기의 효과",
    short_summary: "작은 일정 공유만으로도 주중의 불필요한 연락과 혼선을 줄이는 데 도움이 됩니다.",
    action_line: "오늘 저녁 식사 전후로 이번 주 일정을 한 번 함께 맞춰보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-family-1",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-family-1", type: "other" }],
    slug: "sample-family-schedule",
    published_at: now,
    share_count: 5,
    summary_type: "ACTION",
    main_interest: "가족",
    sub_interest: "집안 일정",
    thumbnail_url: "https://picsum.photos/seed/family1/400/300",
    thumbnail_alt: "가족 일정",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-family-2",
    title: "짧은 안부 전화의 힘",
    short_summary: "긴 대화가 아니어도 자주 연결되는 감각이 서로에게 큰 안심이 될 수 있습니다.",
    action_line: "오늘은 부모님께 짧게 안부 전화를 드려보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-family-2",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-family-2", type: "other" }],
    slug: "sample-family-parents",
    published_at: now,
    share_count: 10,
    summary_type: "USEFUL",
    main_interest: "가족",
    sub_interest: "부모 돌봄",
    thumbnail_url: "https://picsum.photos/seed/parents/400/300",
    thumbnail_alt: "부모님과 통화",
    thumbnail_page_url: null,
    thumbnail_license: null
  },
  {
    id: "demo-family-3",
    title: "자녀와의 짧은 대화도 기록이 됩니다",
    short_summary: "길게 이야기하지 못한 날에도 한두 문장 대화가 관계의 흐름을 이어주는 데 도움이 됩니다.",
    action_line: "오늘은 자녀에게 하루 어땠는지 한 가지만 물어보세요.",
    source_name: "세줄아침 데모",
    source_url: "https://example.com/demo-family-3",
    sources: [{ name: "세줄아침 데모", url: "https://example.com/demo-family-3", type: "other" }],
    slug: "sample-family-talk",
    published_at: now,
    share_count: 7,
    summary_type: "USEFUL",
    main_interest: "가족",
    sub_interest: "자녀 소통",
    thumbnail_url: "https://picsum.photos/seed/children/400/300",
    thumbnail_alt: "자녀와 대화",
    thumbnail_page_url: null,
    thumbnail_license: null
  }
];
